
services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trading_password
      POSTGRES_DB: trading_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: backend-container
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trading_password
      POSTGRES_DB: trading_bot
    ports:
      - "8000:8000"
      - "8765:8765"
    volumes:
      - ../backend:/app

volumes:
  postgres_data:
