
services:
  app:
    build:
      context: ..  # Use parent directory as the build context
      dockerfile: docker/Dockerfile  # Explicitly specify Dockerfile location
    container_name: scalping_bot
    ports:
      - "80:80"  # Frontend served via Nginx
      - "8000:8000"  # Backend API
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/trading_bot
      - REDIS_URL=redis://redis:6379
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: trading_bot
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
